classdef CrossReleaseTestResults < matlab.unittest.TestCase
    % CrossReleaseTestResults
    %
    % Purpose:
    %   Validates matrix test artifacts generated by the multi-release CI
    %   pipeline. This is the guard that confirms all tests passed across
    %   all MATLAB releases tested in CI.
    %
    % CI execution flow:
    %   1) In .github/workflows/ci.yml, job "test-matrix" runs
    %      "buildtool test" for each MATLAB release in the matrix.
    %   2) Each matrix run uploads release-scoped artifacts under
    %      public/<release>/ (including *-results.mat files).
    %   3) Job "report-and-deploy" downloads and merges all matrix artifacts
    %      into a single public/ folder.
    %   4) The same job runs "buildtool report", which triggers
    %      buildfile.m task "report:validate".
    %   5) Task "report:validate" runs this test class, which parameterizes
    %      over public/<release>/*.mat and verifies all result.Passed values.
    %
    % Why this filter exists:
    %   Only MAT files inside public/<release>/ are validated so aggregate
    %   files written at public/ root (for example overall-results.mat)
    %   are not re-checked as input artifacts.

    properties (ClassSetupParameter)
        Project = {currentProject()};
    end

    properties (TestParameter)
        ResultArtifactPath
    end

    methods (TestParameterDefinition, Static)

        function ResultArtifactPath = listReleaseResultArtifacts(Project)
            import matlab.buildtool.io.FileCollection
            rootFolder = Project.RootFolder;
            resultFiles = FileCollection.fromPaths(fullfile(rootFolder, "public","*","*.mat")).paths;
            [filePath, ~, ~] = fileparts(resultFiles);
            [~, folderName, ~] = fileparts(filePath);
            ResultArtifactPath = cellstr(folderName);

            if isempty(resultFiles)
                ResultArtifactPath = {"<NO_RESULT_ARTIFACTS_FOUND>"};
                return;
            end
        end

    end

    methods (TestClassSetup)

        function validateProjectInput(testCase, Project)
            testCase.assertClass(Project, "matlab.project.Project", ...
                "Project must be a matlab.project.Project object.");
        end

    end

    methods (Test)

        function verifyAllTestsPassedInArtifact(testCase, ResultArtifactPath)
            testCase.assertNotEqual(ResultArtifactPath, "<NO_RESULT_ARTIFACTS_FOUND>", ...
                "No per-release result artifacts were found under public/<release>.");

            import matlab.buildtool.io.FileCollection
            rootFolder = testCase.Project{1}.RootFolder;
            resultFiles = FileCollection.fromPaths(fullfile(rootFolder, "public", ResultArtifactPath, "*.mat")).paths;

            allResults = [];
            for i = 1:numel(resultFiles)
                loadedData = load(resultFiles(i), "result");
                testCase.assertTrue(isfield(loadedData, "result"), ...
                    "Missing variable 'result' in artifact: " + resultFiles(i));
                allResults = [allResults, loadedData.result]; %#ok<AGROW>
            end

            testCase.assertNotEmpty(allResults, ...
                "Result array is empty in artifact: " + ResultArtifactPath);

            passedValues = [allResults.Passed];
            testCase.assertNotEmpty(passedValues, ...
                "Result.Passed is empty in artifact: " + ResultArtifactPath);

            testCase.verifyTrue(all(passedValues), ...
                "Some tests did not pass in artifact: " + ResultArtifactPath);
        end

    end

end
